title: Site

tabs:

  content:
    label: Content
    icon: text
    sections:

      pages:
        headline: Pages
        type: pages
        image: false

  settings:
    label: Settings
    icon: cog
    sections:

      fields:
        type: fields
        fields:

          tagline:
            label: Tagline
            type: text
            help: >
              Tagline will be displayed in title tag next to your site name.
              (e.g. {{ site.title }} - Your Custom Tagline)

          social:
            label: Social
            type: structure
            fields:
              name:
                label: Name
                type: text
              code:
                label: Code
                type: text
                help: Font Awesome Unicode code.
              url:
                label: Url
                type: url

          footer:
            label: Footer
            type: textarea
            buttons: false
